---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      name: proxy-deployment
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: docker.io/thealpha16/isolet-proxy
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
            requests:
              memory: "16Mi"
              cpu: "10m"
          ports:
            - containerPort: 80
          env:
            - name: UI_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ui_url
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: api_url
            - name: PROXY_SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: proxy_server_name
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-svc
  labels:
    app: proxy-svc
spec:
  ports:
    - port: 80
  selector:
    app: proxy
  type: NodePort
