---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      name: ui-deployment
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: docker.io/thealpha16/isolet-ui
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1Gi"
              cpu: "300m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ui-svc
  labels:
    app: ui-svc
spec:
  ports:
    - port: 80
  selector:
    app: ui
