---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  session_secret: ODE1NWIyODgwOWQ2MGJlMDQxNjM4N2E5OWM5NDI5NzU=
  token_secret: MTQyNGU2ZjBhMTQ2MzM5Yjc0YWYyNzlkNjRhOTIzNjI=
  email_id: dGVzdGluZy5vbkBteXNlbGYuY29t
  email_auth: aXRzZmFrZWR1ZGU=
  instance_name_secret: N2Q2YzllOGY2ODcwZWZhNGU1YmJiYzU3YjdiY2JmZDM=