---
apiVersion: v1
kind: Secret
metadata:
  name: db-creds
type: Opaque
data:
  db_host: ZGF0YWJhc2Utc3Zj
  db_user: cG9zdGdyZXM=
  db_password: TXlmb290c3Ryb25ncGFzc3dkMDQzLg==
  db_name: cG9zdGdyZXM=