---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: instance-controller
  namespace: isolet
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-instance-controller
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: instance-controller
subjects:
- kind: ServiceAccount
  name: default
  namespace: default